# Generated by Django 3.0.11 on 2021-03-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0015_auto_20180130_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the form.', verbose_name='Description'),
        ),
    ]
