# Generated by Django 3.1.7 on 2021-04-06 05:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0017_formentry_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
