# Generated by Django 3.1.7 on 2021-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0020_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='formelemententry',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
