# Generated by Django 3.1.7 on 2021-04-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0021_formelemententry_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelemententry',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True),
        ),
    ]
