# Generated by Django 3.1.7 on 2021-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0023_formentry_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formelemententry',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
    ]
