# Generated by Django 3.1.7 on 2021-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0024_auto_20210526_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='formelemententry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
