# Generated by Django 3.1.7 on 2021-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0025_formelemententry_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='login_required',
            field=models.BooleanField(default=True),
        ),
    ]
