# Generated by Django 3.1.7 on 2021-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0026_formentry_login_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='add_proofs',
            field=models.BooleanField(default=False),
        ),
    ]
