# Generated by Django 3.2.13 on 2022-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi_contrib_plugins_form_handlers_db_store', '0003_savedformdataentry_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedformdataentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savedformdataentry',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
